export const LOAD_MY_INFO_REQUEST = 'LOAD_MY_INFO_REQUEST' as const
export const LOAD_MY_INFO_SUCCESS = 'LOAD_MY_INFO_SUCCESS' as const
export const LOAD_MY_INFO_FAILURE = 'LOAD_MY_INFO_FAILURE' as const

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST' as const
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS' as const
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE' as const

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST' as const
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS' as const
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE' as const

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST' as const
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS' as const
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE' as const

export const CHANGE_NICKNAME_REQUEST = 'CHANGE_NICKNAME_REQUEST' as const
export const CHANGE_NICKNAME_SUCCESS = 'CHANGE_NICKNAME_SUCCESS' as const
export const CHANGE_NICKNAME_FAILURE = 'CHANGE_NICKNAME_FAILURE' as const

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST' as const
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS' as const
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE' as const

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST' as const
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS' as const
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE' as const

export const LOAD_FOLLOWINGS_REQUEST = 'LOAD_FOLLOWINGS_REQUEST' as const
export const LOAD_FOLLOWINGS_SUCCESS = 'LOAD_FOLLOWINGS_SUCCESS' as const
export const LOAD_FOLLOWINGS_FAILURE = 'LOAD_FOLLOWINGS_FAILURE' as const

export const LOAD_FOLLOWERS_REQUEST = 'LOAD_FOLLOWERS_REQUEST' as const
export const LOAD_FOLLOWERS_SUCCESS = 'LOAD_FOLLOWERS_SUCCESS' as const
export const LOAD_FOLLOWERS_FAILURE = 'LOAD_FOLLOWERS_FAILURE' as const

export const REMOVE_FOLLOWER_REQUEST = 'REMOVE_FOLLOWER_REQUEST' as const
export const REMOVE_FOLLOWER_SUCCESS = 'REMOVE_FOLLOWER_SUCCESS' as const
export const REMOVE_FOLLOWER_FAILURE = 'REMOVE_FOLLOWER_FAILURE' as const

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST' as const
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS' as const
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE' as const

export const ADD_POST_TO_ME = 'ADD_POST_TO_ME' as const
export const REMOVE_POST_OF_ME = 'REMOVE_POST_OF_ME' as const
